### ISSUE TITLE
Basic documentation - HOW TO correctly configure

### ISSUE THREAD

**Issue by ryszard-suchocki** [ZerosRealm/Tergum#2]
Hello,
Unfortunately, I don't know how to correctly configure the server and agent. Would it be possible to create some docs that describe the whole setup? My current is:

Server / `config.yaml`
```yaml
listen:
  ip: "0.0.0.0"
  port: 8083
restic: "/usr/sbin/restic"
database:
  driver: sqlite
  datasourcename: "sqlite.db"
```
Agent / `agent.yml`
```yaml
listen:
  ip: 0.0.0.0
  port: 10000
psk: "80166ce5ee3061bdc496b12681754ebf2a75d571cbd7c6bfdb315c7eaeb73e0e"
restic: "/usr/sbin/restic"
server: "http://localhost"
```
HTTP Server / Caddyfile (Caddy & caddyfile placed in `ui/public/`)
```
:80

reverse_proxy /api/* localhost:8083
root * .
file_server browse

```

Thank you for support.
